const {chromium}=require('C:/Users/openb/.codex/tools/playwright-check/node_modules/playwright');const fs=require('node:fs/promises'),assert=require('node:assert/strict');const before=process.argv.includes('--before'),pub='http://127.0.0.1:'+(before?4200:4202),admin='http://127.0.0.1:'+(before?4201:4203);let results=[],errors=[];
const api=async(path,data)=>fetch(pub+path,{method:data?'POST':'GET',headers:{'content-type':'application/json'},body:data?JSON.stringify(data):undefined}).then(r=>r.json());
(async()=>{const b=await chromium.launch({headless:true});await fs.mkdir(__dirname+'/screenshots',{recursive:true});const c=await b.newContext({viewport:{width:1440,height:1000}});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);
async function test(name,fn){try{results.push({name,status:'PASS',evidence:await fn()})}catch(e){results.push({name,status:'FAIL',error:e.message})}console.log(JSON.stringify(results.at(-1)));await fs.writeFile(__dirname+'/'+(before?'before':'after')+'-core.json',JSON.stringify({results,errors},null,2))}
await test('pickup-only empty cart',async()=>{await api('/__reset',{});await api('/__seed',{settings:{delivery_enabled:false}});await p.goto(pub+'/shop');await p.waitForTimeout(800);const n=await p.getByRole('button',{name:'הוספה',exact:true}).evaluateAll(es=>es.filter(e=>!e.disabled).length);await p.screenshot({path:__dirname+'/screenshots/'+(before?'before':'after')+'-pickup-only.png'});assert.equal(n,before?0:78);return{enabledAdds:n}});
await api('/__reset',{});await p.goto(admin+'/login');await p.getByRole('button',{name:'התחברות',exact:true}).click();await p.getByRole('heading',{name:'דשבורד',exact:true}).waitFor();
await test('concurrent product saves',async()=>{await p.goto(admin+'/products');await p.locator('.product-row').first().waitFor();await api('/__control',{delay:1800});const rows=p.locator('.product-row');await rows.nth(0).locator('.availability-button').click();await rows.nth(1).getByRole('button',{name:/מחיר/}).click();await p.getByRole('dialog').locator('input').fill('88');await p.getByRole('dialog').getByRole('button',{name:/שמירת/}).click();await p.waitForTimeout(2400);const s=await api('/__state');assert.equal(s.log.filter(x=>x.table==='products').length,before?1:2);return{writes:s.log}});
await test('stale settings unrelated edit',async()=>{await api('/__reset',{});await p.goto(admin+'/settings');await p.locator('#customer-notice').waitFor();await api('/__seed',{settings:{delivery_enabled:false}});await p.locator('.toggle-row').nth(3).click();await p.locator('#customer-notice').fill('הודעת בדיקה חדשה');await p.getByRole('button',{name:'שמירת שינויים',exact:true}).click();await p.waitForTimeout(500);const s=await api('/__state');assert.equal(s.db.store_settings.delivery_enabled,before);return{delivery:s.db.store_settings.delivery_enabled,writes:s.log}});
await b.close();if(results.some(r=>r.status==='FAIL'))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
