const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=__dirname,original=JSON.parse(fs.readFileSync(path.join(root,'public-fixtures.json'),'utf8'));let db,log=[],controls={},version=Date.now();const stamp=()=>new Date(Math.max(Date.now(),++version)).toISOString();
const reset=()=>{db=structuredClone(original);db.store_settings.id='default';db.categories.forEach(x=>x.active=true);db.products.forEach(x=>x.updated_at=db.store_settings.updated_at);log=[];controls={}};reset();
const user={id:'11111111-1111-4111-8111-111111111111',aud:'authenticated',role:'authenticated',email:'audit@example.invalid',app_metadata:{provider:'email',providers:['email']},user_metadata:{},created_at:new Date().toISOString()};const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');
const session=()=>({access_token:enc({alg:'HS256',typ:'JWT'})+'.'+enc({sub:user.id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})+'.local-only',token_type:'bearer',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,refresh_token:'local-only',user});
const beforeDb=JSON.parse(fs.readFileSync(path.join(root,'before-public-fixtures.json'),'utf8'));
beforeDb.store_settings.id='default';beforeDb.categories.forEach(x=>x.active=true);beforeDb.products.forEach(x=>x.updated_at=beforeDb.store_settings.updated_at);
const injection='<script>'+fs.readFileSync(path.join(root,'preview-injection.js'),'utf8')+'</script>';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.mp4':'video/mp4','.woff2':'font/woff2','.json':'application/json'};
for(const [port,dir] of [[4200,'../bakery-polish-20260912/project/dist'],[4201,'../bakery-polish-20260912/project/admin-dashboard/dist'],[4202,'project/dist'],[4203,'project/admin-dashboard/dist']]){const dist=path.resolve(root,dir);http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');const json=(v,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(v))};let body='';for await(const c of req)body+=c;const payload=body?JSON.parse(body):{};
if(u.pathname==='/__reset'){reset();return json({ok:true})}if(u.pathname==='/__state')return json({db,log,controls});if(u.pathname==='/__control'){Object.assign(controls,payload);return json({ok:true})}if(u.pathname==='/__seed'){if(payload.settings)Object.assign(db.store_settings,payload.settings,{updated_at:stamp()});if(payload.product)Object.assign(db.products.find(x=>x.id===payload.product.id),payload.product);if(payload.option)Object.assign(db.product_options.find(x=>x.id===payload.option.id),payload.option);return json({ok:true})}
if(u.pathname.startsWith('/__api/auth/')){if(u.pathname.endsWith('/logout')){res.writeHead(204).end();return}return json(u.pathname.endsWith('/user')?user:session())}
if(u.pathname.startsWith('/__api/rest/')){const table=u.pathname.split('/').pop();const readDb=port<4202?beforeDb:db;if(port<4202&&req.method!=='GET')return json({message:'Before snapshot is read only'},403);let rows=table==='admin_users'?[{user_id:user.id,display_name:'מנהל בדיקה',role:'owner',active:true}]:table==='store_settings'?[readDb.store_settings]:readDb[table];if(!rows)return json({message:'Unknown local fixture table'},404);const single=(req.headers.accept||'').includes('application/vnd.pgrst.object');
if(req.method==='GET'){if(controls.failRead===table)return json({message:'Simulated read failure'},503);for(const [k,v]of u.searchParams)if(v.startsWith('eq.'))rows=rows.filter(r=>String(r[k])===v.slice(3));return json(single?rows[0]??null:rows)}
if(req.method==='PATCH'&&['products','store_settings'].includes(table)){if(controls.casDelay&&table==='store_settings')await new Promise(r=>setTimeout(r,controls.casDelay));if(controls.delay&&table==='products')await new Promise(r=>setTimeout(r,controls.delay));if(controls.failWrite===table)return json({message:'Simulated save failure'},403);for(const [k,v]of u.searchParams)if(v.startsWith('eq.'))rows=rows.filter(r=>String(r[k])===v.slice(3));if(rows.length){Object.assign(rows[0],payload,{updated_at:stamp()});log.push({table,patch:payload});if(controls.readMismatch===table)Object.assign(rows[0],table==='products'?{price_agorot:1}:{customer_notice_text:'Mismatch'});if(controls.failReadAfter===table)controls.failRead=table;}return json(single?(rows[0]?{id:rows[0].id}:null):rows.map(x=>({id:x.id})))}return json({message:'Unsupported local write'},403)}
if(u.pathname==='/__order'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end('<html dir="rtl"><h1>הזמנת בדיקה — לא נשלחה</h1><pre id="text"></pre><script>text.textContent=sessionStorage.getItem("preview-last-order")||"טרם נוצרה הזמנת בדיקה"</script></html>')}
let name=path.resolve(dist,'.'+decodeURIComponent(u.pathname));if(!name.startsWith(dist+path.sep)&&name!==dist){res.writeHead(403).end();return}if(!fs.existsSync(name)||fs.statSync(name).isDirectory())name=path.join(dist,'index.html');if(!fs.existsSync(name)){res.writeHead(503).end('Local preview rebuilding');return}res.setHeader('Content-Type',mime[path.extname(name)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"connect-src 'self'; form-action 'self'");if(path.extname(name)==='.html')return res.end(fs.readFileSync(name,'utf8').replace('<head>','<head>'+injection));fs.createReadStream(name).on('error',()=>res.end()).pipe(res);
}).listen(port,'127.0.0.1',()=>console.log('safe local preview '+port));}