const{chromium}=require('C:/Users/openb/.codex/tools/playwright-check/node_modules/playwright');const fs=require('node:fs/promises'),assert=require('node:assert/strict');
const U='http://127.0.0.1:4182',A='http://127.0.0.1:4183';const api=(path,data)=>fetch(U+path,{method:data?'POST':'GET',headers:{'content-type':'application/json'},body:data?JSON.stringify(data):undefined}).then(r=>r.json());let results=[],errors=[],browser;
const card=(p,n)=>p.locator('.shop-product-card').filter({has:p.getByRole('heading',{name:n,exact:true})});
const add=(p,n)=>card(p,n).getByRole('button',{name:'הוספה',exact:true}).click();
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function test(name,fn){await api('/__reset',{});let c;try{c=await browser.newContext({viewport:{width:1440,height:1000}});c.on('page',p=>{p.on('pageerror',e=>errors.push({name,error:e.message}));p.setDefaultTimeout(15000)});const p=await c.newPage();results.push({name,status:'PASS',evidence:await fn(p,c)})}catch(e){results.push({name,status:'FAIL',error:e.message})}finally{if(c)await c.close()}console.log(JSON.stringify(results.at(-1)));await fs.writeFile(__dirname+'/regression.json',JSON.stringify({results,errors},null,2))}
async function shop(p){await p.goto(U+'/shop');await p.getByRole('button',{name:'הוספה',exact:true}).first().waitFor()}
async function login(p){await p.goto(A+'/login');if(await p.getByRole('button',{name:'התחברות',exact:true}).count())await p.getByRole('button',{name:'התחברות',exact:true}).click();await p.getByRole('heading',{name:'דשבורד',exact:true}).waitFor()}
async function details(p){await p.getByRole('button',{name:'המשך לפרטי הזמנה',exact:true}).click();await p.locator('#checkout-customerName').fill('בדיקת תיקון');await p.locator('#checkout-phone').fill('0500000000');await p.locator('#checkout-notes').fill('בדיקה בלבד')}
async function address(p){await p.locator('#checkout-street').fill('רחוב בדיקה');await p.locator('#checkout-houseNumber').fill('3');await p.locator('#checkout-floor').fill('2');await p.locator('#checkout-apartment').fill('4')}
async function send(p){await p.getByRole('button',{name:'שליחת ההזמנה בוואטסאפ',exact:true}).click();await pause(350);return p.evaluate(()=>window.previewOrders)}
async function priceDialog(p,row=0){await p.goto(A+'/products');await p.locator('.product-row').nth(row).locator('.edit-price-button').click()}
(async()=>{browser=await chromium.launch({headless:true});
await test('price card-cart-checkout-handoff update and rounding',async p=>{await shop(p);await add(p,'מים מינרליים');await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();await details(p);const s=await api('/__state');const water=s.db.products.find(x=>x.name_he==='מים מינרליים');await api('/__seed',{product:{id:water.id,price_agorot:1234}});assert.equal((await send(p)).length,0);assert.match(await p.locator('.shop-cart-panel').innerText(),/12.34/);const messages=await send(p);assert.equal(messages.length,1);assert.match(messages[0],/12.34/);assert.doesNotMatch(messages[0],/100 מל/);await p.reload();await p.waitForTimeout(500);assert.match(await card(p,'מים מינרליים').innerText(),/12.34/);return{currentPriceAgorot:1234,staleComparisonRemoved:true,handoff:messages[0]}});
await test('delivery pickup switches preserve address and correct fees',async p=>{await shop(p);await add(p,'1 ק״ג בורקסים מיקס הפתעה');await details(p);await address(p);await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();let m=await send(p);assert.match(m[0],/איסוף עצמי/);assert.doesNotMatch(m[0],/רחוב בדיקה/);await p.getByRole('radio',{name:'משלוח',exact:true}).check();assert.equal(await p.locator('#checkout-street').inputValue(),'רחוב בדיקה');m=await send(p);assert.match(m[1],/85/);assert.match(m[1],/רחוב בדיקה/);return{pickup70:true,delivery85:true,addressRetained:true}});
await test('back forward and refresh preserve populated cart',async p=>{await shop(p);await add(p,'מים מינרליים');await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();await p.locator('.shop-cover-link').click();await p.goBack();await p.waitForTimeout(500);assert.equal(await p.locator('.shop-cart-item').count(),1);assert(await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).isChecked());await p.goForward();await p.goBack();await p.reload();await p.waitForTimeout(500);assert.equal(await p.locator('.shop-cart-item').count(),1);return{history:true,refresh:true}});
await test('invalid persisted state does not deadlock checkout',async(p,c)=>{await c.addInitScript(()=>sessionStorage.setItem('yachad-checkout-v1','{"version":1,"fulfillment":"invalid","cart":{"bad":{"quantity":-2}}}'));await shop(p);assert.equal(await p.locator('.shop-cart-item').count(),0);await add(p,'1 ק״ג בורקסים מיקס הפתעה');assert.equal(await p.locator('.shop-cart-item').count(),1);return{invalidItemDiscarded:true}});
await test('closed fulfillment recovers without emptying cart',async p=>{await shop(p);await add(p,'מים מינרליים');await api('/__seed',{settings:{delivery_enabled:false,pickup_enabled:false}});await p.evaluate(()=>dispatchEvent(new Event('focus')));await pause(500);assert(await p.getByRole('button',{name:'המשך לפרטי הזמנה',exact:true}).isDisabled());assert.equal(await p.locator('.shop-cart-item').count(),1);await api('/__seed',{settings:{pickup_enabled:true}});await p.evaluate(()=>dispatchEvent(new Event('focus')));await pause(500);assert(await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).isChecked());assert(!(await p.getByRole('button',{name:'המשך לפרטי הזמנה',exact:true}).isDisabled()));return{cartRetained:true,recovered:true}});
await test('pickup-exclusive product accessible with empty cart',async p=>{const s=await api('/__state');const x=s.db.products.find(x=>x.name_he==='מים מינרליים');await api('/__seed',{product:{id:x.id,available_for_delivery:false}});await shop(p);await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();await add(p,'מים מינרליים');assert.equal(await p.locator('.shop-cart-item').count(),1);return{exclusiveProductAdded:true}});
await test('explicit 550g unit reprices from current money',async p=>{const s=await api('/__state');const bread=s.db.products.find(x=>x.description_he.includes('550 גרם'));await api('/__seed',{product:{id:bread.id,price_agorot:3333}});await shop(p);const text=await card(p,bread.name_he).innerText();assert.match(text,/33.33/);assert.match(text,/6.06/);await add(p,bread.name_he);await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();await p.locator('.shop-cart-panel').getByRole('button',{name:'הוספת '+bread.name_he,exact:true}).click();assert.match(await p.locator('.shop-totals').innerText(),/66.66/);return{text,totalAgorot:6666}});
await test('salad selections and charges survive refresh',async p=>{await shop(p);await add(p,'סלט ירקות בהרכבה');const d=p.getByRole('dialog');await d.getByRole('checkbox').first().check();const chosen=await d.getByRole('checkbox').first().getAttribute('value');await d.getByRole('button',{name:'הוספה להזמנה',exact:true}).click();await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();const old=await p.locator('.shop-cart-item').innerText();await p.reload();await pause(500);assert.equal(await p.locator('.shop-cart-item').innerText(),old);await details(p);assert.equal((await send(p)).length,1);return{chosen,selectionRetained:true}});
await test('admin comma price saved readback navigation refresh',async p=>{await login(p);await priceDialog(p);await p.locator('#product-price').fill('12,34');await p.getByRole('button',{name:'שמירת מחיר',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});await p.goto(A+'/settings');await p.goto(A+'/products');await p.reload();await p.locator('.product-row').first().waitFor();assert.match(await p.locator('.product-row').first().innerText(),/12.34/);const s=await api('/__state');assert.equal(s.log[0].patch.price_agorot,1234);return{storedAgorot:1234,refresh:true}});
for(const mode of ['failWrite','readMismatch','failReadAfter'])await test('product failure feedback '+mode,async p=>{await login(p);await priceDialog(p);await api('/__control',{[mode]:'products'});await p.locator('#product-price').fill('44');await p.getByRole('button',{name:'שמירת מחיר',exact:true}).click();await p.locator('#product-price-error').waitFor({timeout:30000});assert(await p.getByRole('dialog').isVisible());assert.equal(await p.locator('#product-price').inputValue(),'44');assert.equal(await p.getByText('המחיר נשמר ואומת',{exact:true}).count(),0);return{error:await p.locator('#product-price-error').innerText(),draftRetained:true}});
await test('duplicate price submit issues one write and locks input',async p=>{await login(p);await priceDialog(p);await api('/__control',{delay:800});await p.locator('#product-price').fill('44');await p.getByRole('dialog').locator('form').evaluate(f=>{f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))});assert(await p.locator('#product-price').isDisabled());await p.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await api('/__state')).log.length,1);return{writes:1}});
await test('concurrent fulfillment CAS rejects impossible state',async(p,c)=>{await login(p);const p2=await c.newPage();await p.goto(A+'/settings');await p2.goto(A+'/settings');await p.locator('.toggle-row').nth(1).click();await p2.locator('.toggle-row').nth(2).click();await api('/__control',{casDelay:200});await Promise.all([p.getByRole('button',{name:'שמירת שינויים',exact:true}).click(),p2.getByRole('button',{name:'שמירת שינויים',exact:true}).click()]);await pause(1000);const s=await api('/__state');assert(s.db.store_settings.delivery_enabled||s.db.store_settings.pickup_enabled);assert.equal(s.log.length,1);const text=(await p.locator('body').innerText())+(await p2.locator('body').innerText());assert.match(text,/לפחות משלוח או איסוף עצמי/);return{settings:s.db.store_settings,writes:s.log}});
await test('mobile settings error stays visible after toast',async p=>{await p.setViewportSize({width:390,height:844});await login(p);await p.goto(A+'/settings');await p.locator('.toggle-row').nth(3).click();await p.locator('#customer-notice').fill('הודעת בדיקה לנייד');await api('/__control',{failWrite:'store_settings'});await p.getByRole('button',{name:'שמירת שינויים',exact:true}).click();await p.locator('.validation-note[role=alert]').waitFor();await pause(4000);await p.locator('.validation-note[role=alert]').scrollIntoViewIfNeeded();assert(await p.locator('.validation-note[role=alert]').isVisible());await p.screenshot({path:__dirname+'/screenshots/mobile-save-error.png'});return{persistentError:true}});
await test('settings noop does not write',async p=>{await login(p);await p.goto(A+'/settings');assert(await p.getByRole('button',{name:'שמירת שינויים',exact:true}).isDisabled());assert.equal((await api('/__state')).log.length,0);return{writes:0}});
await browser.close();if(results.some(x=>x.status==='FAIL')||errors.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
