const{chromium}=require('C:/Users/openb/.codex/tools/playwright-check/node_modules/playwright');const fs=require('node:fs/promises');const root=__dirname;let checks=[],errors=[],failed=[];
(async()=>{await fetch('http://127.0.0.1:4182/__reset',{method:'POST',body:'{}'});const b=await chromium.launch({headless:true});for(const width of [390,768,1440])for(const phase of ['before','after']){const pub='http://127.0.0.1:'+(phase==='before'?4180:4182),admin='http://127.0.0.1:'+(phase==='before'?4181:4183);const c=await b.newContext({viewport:{width,height:width===390?844:1000},hasTouch:width===390,isMobile:width===390});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('requestfailed',r=>{if(!r.failure()?.errorText.includes('ABORTED'))failed.push({phase,width,url:r.url(),error:r.failure()?.errorText})});await p.clock.setFixedTime(new Date('2026-09-12T09:00:00Z'));
async function shot(name){await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(300);const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);const filename=phase+'-'+name+'-'+width+'.png';await p.screenshot({path:root+'/screenshots/'+filename});checks.push({phase,name,width,overflow,file:filename})}
await p.goto(pub+'/');await p.waitForTimeout(1400);await shot('home');await p.locator('.cinematic-intro__skip').click();await p.waitForTimeout(500);await shot('home-welcome');
await p.goto(pub+'/shop');await p.getByRole('button',{name:'הוספה',exact:true}).first().waitFor();await p.waitForTimeout(900);await shot('shop');
await p.locator('.shop-product-card').filter({has:p.getByRole('heading',{name:'מים מינרליים',exact:true})}).getByRole('button',{name:'הוספה',exact:true}).click();if(width<1024)await p.locator('.shop-mobile-cart-button').click();await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();await shot('cart');
await p.getByRole('button',{name:'המשך לפרטי הזמנה',exact:true}).click();await p.locator('#checkout-customerName').fill('בדיקת מסך');await p.locator('#checkout-phone').fill('0500000000');await p.locator('#checkout-notes').fill('בדיקה בלבד');await shot('checkout');
await p.goto(admin+'/login');await p.getByRole('button',{name:'התחברות',exact:true}).click();await p.getByRole('heading',{name:'דשבורד',exact:true}).waitFor();await shot('admin');
await p.goto(admin+'/products');await p.getByRole('heading',{name:'מה זמין היום?',exact:true}).waitFor();await shot('admin-products');
const priceButton=p.locator('.edit-price-button:visible').first();await priceButton.click();await shot('admin-price');await p.getByRole('button',{name:'סגירת חלון',exact:true}).click();
await p.goto(admin+'/settings');await p.getByRole('heading',{name:'שליטה במה שהלקוחות רואים',exact:true}).waitFor();await shot('admin-settings');await c.close();console.log(phase+' '+width+' complete')}await b.close();await fs.writeFile(root+'/visual-checks.json',JSON.stringify({checks,errors,failed},null,2));console.log('screenshots '+checks.length)})().catch(e=>{console.error(e);process.exit(1)});