
const fs=require('node:fs'),path=require('node:path');const base=__dirname,md=fs.readFileSync(path.join(base,'REPORT.md'),'utf8'),findings=JSON.parse(fs.readFileSync(path.join(base,'findings.json'),'utf8'));
const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function inline(s){const t=[];s=s.replace(/`([^`]+)`/g,(_,v)=>{t.push('<code dir="ltr">'+esc(v)+'</code>');return '§T'+(t.length-1)+'§'}).replace(/\[([^\]]+)\]\((?:<([^>]+)>|([^)]+))\)/g,(_,label,a,b)=>{t.push('<a href="'+esc(a||b)+'">'+esc(label)+'</a>');return '§T'+(t.length-1)+'§'});return esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/§T(\d+)§/g,(_,i)=>t[+i]);}
function render(text){const lines=text.split('\n');let html='',list='',code=false,buf=[];const flush=()=>{if(buf.length){html+='<p>'+inline(buf.join(' '))+'</p>';buf=[]}};const close=()=>{if(list){html+='</'+list+'>';list=''}};for(let i=0;i<lines.length;i++){let l=lines[i];if(l.startsWith('```')){flush();close();html+=code?'</code></pre>':'<pre dir="ltr"><code>';code=!code;continue;}if(code){html+=esc(l)+'\n';continue;}if(!l.trim()){flush();close();continue;}if(l.startsWith('|')){flush();close();let rows=[];while(i<lines.length&&lines[i].startsWith('|'))rows.push(lines[i++]);i--;const cells=v=>v.split('|').slice(1,-1).map(c=>c.trim());html+='<div class="table-wrap"><table><thead><tr>'+cells(rows[0]).map(c=>'<th>'+inline(c)+'</th>').join('')+'</tr></thead><tbody>';for(const row of rows.slice(2))html+='<tr>'+cells(row).map(c=>'<td>'+inline(c)+'</td>').join('')+'</tr>';html+='</tbody></table></div>';continue;}const h=l.match(/^(#{1,4}) (.+)$/);if(h){flush();close();const n=h[1].length,m=h[2].match(/^(\d+)\./);html+='<h'+n+(m?' id="section-'+m[1]+'"':'')+'>'+inline(h[2])+'</h'+n+'>';continue;}const li=l.match(/^(-|\d+\.) (.+)$/);if(li){flush();const type=li[1]==='-'?'ul':'ol';if(list!==type){close();html+='<'+type+'>';list=type}html+='<li>'+inline(li[2])+'</li>';continue;}buf.push(l);}flush();close();return html;}
const before=md.slice(0,md.indexOf('\n### אתר ציבורי')),after=md.slice(md.indexOf('\n## 5.'));
let cards='<div class="filters"><label for="filter">הצגת ממצאים</label><select id="filter"><option value="all">כל 32 הממצאים</option><option value="urgent">P0 + P1 — מהותיים</option><option value="P2">P2 — ערך גבוה</option><option value="P3">P3 — ליטוש</option></select><button id="expand">פתיחת כל הממצאים</button></div>';
for(const section of ['אתר ציבורי','חנות','אדמין','רוחבי']){cards+='<section class="findings-group"><h3>'+esc(section)+'</h3>';for(const x of findings.filter(f=>f.section===section)){cards+='<details class="finding" id="'+x.id+'" data-priority="'+x.priority+'"'+(['P0','P1'].includes(x.priority)?' open':'')+'><summary><span class="priority '+x.priority+'">'+x.priority+'</span><span><b>'+x.id+' · '+esc(x.title)+'</b><small>'+esc(x.kind)+' · '+esc(x.effort)+'</small></span></summary><div class="finding-content">';for(const [title,value]of[['מה נמצא',x.evidence],['השפעה',x.impact],['המלצה',x.recommendation],['מועד',x.timing]])cards+='<p><b>'+title+':</b> '+esc(value)+'</p>';cards+='<p class="refs"><b>מקור:</b> '+x.refs.map(([p,n])=>'<a href="checkpoint-20260912/release-cc89bd5/'+encodeURI(p)+'"><bdi>'+esc(p)+':'+n+'</bdi></a>').join(' · ')+(x.artifact?' · <a href="'+esc(x.artifact)+'">נתוני הבדיקה</a>':'')+'</p>';if(x.shot)cards+='<figure><a href="screenshots/'+x.shot+'"><img src="screenshots/'+x.shot+'" alt="'+esc(x.title)+' — צילום דפדפן" loading="lazy"></a><figcaption>'+esc(x.shot)+' · לחצו לפתיחה בגודל מלא</figcaption></figure>';cards+='</div></details>';}cards+='</section>';}
const css=fs.readFileSync(path.join(base,'report.css'),'utf8');
const html='<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>ביקורת מאפיית יחד — 12.09.2026</title><style>'+css+'</style></head><body><header><p>מאפיית יחד · ביקורת קוד, קנייה וניהול<br>12.09.2026 · סקירה בלבד</p><a href="REPORT.md">גרסת Markdown</a></header><main><nav class="toc" aria-label="תוכן הדוח"><a href="#section-1">שחזור וגרסה</a><a href="#section-2">מה נבדק</a><a href="#section-3">מה לשמר</a><a href="#section-4">32 ממצאים</a><a href="#section-5">עדיפויות</a><a href="#section-6">שלבי המשך</a><a href="#section-7">בדיקות</a><a href="#section-10">חמשת הראשונים</a></nav>'+render(before)+cards+render(after)+'</main><footer>תוצר ביקורת מקומי. המוצר, הפריסות והנתונים נשמרו ללא שינוי. צילומי אדמין ותרחישי קצה מבוססים על נתוני בדיקה.</footer><script>document.getElementById("filter").addEventListener("change",e=>{document.querySelectorAll(".finding").forEach(d=>{const p=d.dataset.priority,v=e.target.value;d.hidden=!(v==="all"||v===p||(v==="urgent"&&(p==="P0"||p==="P1")))});document.querySelectorAll(".findings-group").forEach(g=>g.hidden=![...g.querySelectorAll(".finding")].some(d=>!d.hidden))});document.getElementById("expand").addEventListener("click",()=>document.querySelectorAll(".finding").forEach(d=>d.open=true));addEventListener("beforeprint",()=>{document.querySelectorAll(".findings-group").forEach(g=>g.hidden=false);document.querySelectorAll(".finding").forEach(d=>{d.hidden=false;d.open=true})});</script></body></html>';
fs.writeFileSync(path.join(base,'REPORT.html'),html);console.log(JSON.stringify({findings:findings.length,htmlBytes:Buffer.byteLength(html),markdownBytes:Buffer.byteLength(md)}));
