
const {chromium}=require('C:/Users/openb/.codex/tools/playwright-check/node_modules/playwright');const fs=require('node:fs/promises'),path=require('node:path');
const base=__dirname,shots=path.join(base,'screenshots'),url='http://127.0.0.1:4175/shop';
(async()=>{const browser=await chromium.launch({headless:true});const initial=JSON.parse(await fs.readFile(path.join(base,'public-fixtures.json'),'utf8'));const findings=[],errors=[];
async function open(width=1440,alter=()=>{}){const data=structuredClone(initial);alter(data);const c=await browser.newContext({viewport:{width,height:width<768?844:1000},hasTouch:width<768,isMobile:width<768});let requests=[],externalWrites=0;await c.route('**/*',async r=>{const req=r.request(),u=new URL(req.url());if(u.hostname.endsWith('.supabase.co')){requests.push({method:req.method(),table:u.pathname.split('/').pop()});const v=data[u.pathname.split('/').pop()];if(data.fail)return r.fulfill({status:503,contentType:'application/json',body:'{"message":"audit simulated outage"}'});return v?r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(v)}):r.abort();}if(!['GET','HEAD'].includes(req.method())||/wa\.me|whatsapp/.test(u.hostname)){externalWrites++;return r.abort();}return r.continue();});await c.routeWebSocket('**/*',ws=>ws.close());await c.addInitScript(()=>{window.auditOpened=[];window.open=(u)=>{if(u)window.auditOpened.push(u);return{opener:null,location:{set href(v){window.auditOpened.push(v)}},close(){window.auditPopupClosed=true}}};window.auditCopied=[];Object.defineProperty(navigator,'clipboard',{value:{writeText:async t=>window.auditCopied.push(t)}});});const p=await c.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));await p.goto(url,{waitUntil:'domcontentloaded'});await p.waitForTimeout(700);return{p,c,data,requests};}
async function test(name,fn){try{const r=await fn();findings.push({name,...r});console.log(name+': '+JSON.stringify(r));}catch(e){findings.push({name,testError:e.message});console.log(name+': TEST ERROR '+e.message);}await fs.writeFile(path.join(base,'shop-extra-results.json'),JSON.stringify({findings,errors},null,2));}
const card=(p,text)=>p.locator('.shop-product-card').filter({has:p.getByRole('heading',{name:text,exact:true})});
const add=async(p,text)=>await card(p,text).getByRole('button',{name:'הוספה',exact:true}).click();
const totals=async p=>await p.locator('.shop-totals').innerText();
async function details(p){await p.getByRole('button',{name:'המשך לפרטי הזמנה',exact:true}).click();await p.locator('#checkout-customerName').waitFor();}
async function fillBasic(p){await p.locator('#checkout-customerName').fill('בדיקת ביקורת');await p.locator('#checkout-phone').fill('0500000000');await p.locator('#checkout-notes').fill('בדיקה בלבד, לא לשלוח');}
async function summary(p){await p.getByRole('button',{name:'שליחת ההזמנה בוואטסאפ',exact:true}).click();await p.waitForTimeout(400);return p.evaluate(()=>window.auditOpened.filter(x=>String(x).includes('wa.me')).map(x=>new URL(x).searchParams.get('text')));}

await test('quantity remove and two salad configurations',async()=>{const{p,c}=await open();await add(p,'1 ק״ג בורקסים מיקס הפתעה');await p.locator('.shop-cart-panel').getByRole('button',{name:'הוספת 1 ק״ג בורקסים מיקס הפתעה',exact:true}).click();const doubled=await totals(p);await p.locator('.shop-cart-panel').getByRole('button',{name:'הפחתת 1 ק״ג בורקסים מיקס הפתעה',exact:true}).click();const reduced=await totals(p);await p.getByRole('button',{name:'הסרת 1 ק״ג בורקסים מיקס הפתעה',exact:true}).click();const empty=await p.getByText('ההזמנה שלך ריקה',{exact:true}).count()>0;for(const i of [0,1]){await add(p,'סלט ירקות בהרכבה');await p.getByRole('dialog').getByRole('checkbox').nth(i).check();await p.getByRole('button',{name:'הוספה להזמנה',exact:true}).click();}const variants=await p.locator('.shop-cart-item').count();const cart=await p.locator('.shop-cart-panel').innerText();await c.close();return{doubled,reduced,empty,variants,cart};});
await test('mobile category dialog focus and hidden cart Tab',async()=>{const{p,c}=await open(390);await p.getByRole('button',{name:'כל הקטגוריות',exact:true}).click();const listCount=await p.getByRole('dialog').getByRole('button').count();await p.getByRole('dialog').getByRole('button',{name:'שתייה',exact:true}).click();const drinks=await p.locator('.shop-product-card').count();await add(p,'מים מינרליים');const autoOpened=await p.locator('.shop-cart-panel').evaluate(e=>e.classList.contains('is-open'));await p.locator('.shop-product-card').last().getByRole('button').last().focus();await p.keyboard.press('Tab');await p.waitForTimeout(500);const tabFocus=await p.evaluate(()=>({tag:document.activeElement.tagName,label:document.activeElement.getAttribute('aria-label'),insideCart:!!document.activeElement.closest('.shop-cart-panel'),rect:document.activeElement.getBoundingClientRect().toJSON(),innerHeight}));await p.locator('.shop-mobile-cart-button').click();await p.getByRole('button',{name:'סגור הזמנה',exact:true}).click();await p.waitForTimeout(600);await p.getByRole('button',{name:'סגור הזמנה',exact:true}).focus();const closedFocus=await p.evaluate(()=>({label:document.activeElement.getAttribute('aria-label'),y:document.activeElement.getBoundingClientRect().y,innerHeight}));await c.close();return{listCount,drinks,autoOpened,tabFocus,closedFocus};});
await test('entire catalog image availability',async()=>{const{p,c}=await open();let imageFailures=[];p.on('requestfailed',r=>{if(r.resourceType()==='image')imageFailures.push(r.url());});let h=await p.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<h;y+=700){await p.evaluate(y=>window.scrollTo(0,y),y);await p.waitForTimeout(70);}await p.waitForTimeout(1800);const images=await p.locator('.shop-product-card img').evaluateAll(es=>({total:es.length,loaded:es.filter(e=>e.complete&&e.naturalWidth>0).length,broken:es.filter(e=>e.complete&&!e.naturalWidth).map(e=>e.alt),pending:es.filter(e=>!e.complete).length}));await c.close();return{images,imageFailures};});
await browser.close();console.log('COMPLETE '+findings.length+' cases');})().catch(e=>{console.error(e.stack);process.exitCode=1});