const {chromium}=require('C:/Users/openb/.codex/tools/playwright-check/node_modules/playwright');
const fs=require('node:fs/promises'),assert=require('node:assert/strict');
const U='http://127.0.0.1:4202',A='http://127.0.0.1:4203';
const api=(s,d)=>fetch(U+s,{method:d?'POST':'GET',headers:{'content-type':'application/json'},body:d?JSON.stringify(d):undefined}).then(r=>r.json());
const card=(p,name)=>p.locator('.shop-product-card').filter({has:p.getByRole('heading',{name,exact:true})});
(async()=>{
 const b=await chromium.launch({headless:true}),results=[];
 const manifest=JSON.parse(await fs.readFile(__dirname+'/evidence/restored-content.json'));
 const data=JSON.parse(await fs.readFile(__dirname+'/public-fixtures.json'));
 const old=JSON.parse(await fs.readFile(__dirname+'/before-public-fixtures.json'));
 const source=JSON.parse(await fs.readFile(__dirname+'/project/product-catalog-yachad.json'));
 for(const product of data.products){const baseline=old.products.find(x=>x.id===product.id);assert.equal(product.price_agorot,baseline.price_agorot);assert.equal(product.price_unit_note,baseline.price_unit_note);if(manifest.descriptionIds.includes(product.id))assert.equal(product.description_he,source.products.find(x=>x.id===product.id).source_10bis_description);}
 for(const width of [390,768,1440]){
  await api('/__reset',{});const c=await b.newContext({viewport:{width,height:width===390?844:1000}}),p=await c.newPage(),errors=[];p.setDefaultTimeout(15000);p.on('pageerror',e=>errors.push(e.message));
  await p.goto(U+'/shop/');await p.locator('.shop-product-card').first().waitFor();
  for(const id of manifest.descriptionIds){const product=data.products.find(x=>x.id===id);assert((await card(p,product.name_he).locator('p').allTextContents()).includes(product.description_he),id);}
  for(const id of ['drinks-02','cakes-01']){const product=data.products.find(x=>x.id===id),item=card(p,product.name_he);await item.scrollIntoViewIfNeeded();await p.waitForFunction(id=>{const e=document.querySelector('img[src="/product-images/'+id+'.jpg"]');return e?.complete&&e.naturalWidth>0},id);await item.screenshot({path:__dirname+'/screenshots/after-'+id+'-'+width+'.png'});}
  for(const id of manifest.pizzas){
   const product=data.products.find(x=>x.id===id);await card(p,product.name_he).getByRole('button').click();const d=p.getByRole('dialog',{name:product.name_he,exact:true});await d.waitFor();assert.equal(await d.getByRole('checkbox').count(),8);assert.match(await d.innerText(),/תוספת אחת כלולה במחיר/);assert.match(await d.innerText(),/תוספות בתשלום יש לתאם/);
   await d.getByRole('button',{name:'הוספה להזמנה',exact:true}).click();await d.locator('.shop-option-error').waitFor();await d.getByRole('checkbox',{name:'זיתי קלמטה',exact:true}).check();await d.getByRole('checkbox',{name:'זיתים ירוקים',exact:true}).check();assert.equal(await d.locator('input:checked').count(),1);await d.getByRole('checkbox',{name:'תירס',exact:true}).check();assert.equal(await d.locator('input:checked').count(),1);assert.match(await d.locator('.shop-option-footer').innerText(),new RegExp(String(product.price_agorot/100)));
   await p.screenshot({path:__dirname+'/screenshots/pizza-'+id+'-'+width+'.png'});await d.getByRole('button',{name:'הוספה להזמנה',exact:true}).click();await d.waitFor({state:'hidden'});
  }
  await p.reload();await p.locator('.shop-product-card').first().waitFor();if(width<1000)await p.locator('.shop-mobile-cart-button').click();
  const cart=p.locator('.shop-cart-panel');assert.match(await cart.innerText(),/תירס/);await p.getByRole('radio',{name:'איסוף עצמי',exact:true}).check();await p.getByRole('button',{name:'המשך לפרטי הזמנה',exact:true}).click();await p.locator('#checkout-customerName').fill('בדיקת שחזור');await p.locator('#checkout-phone').fill('0500000000');await p.getByRole('button',{name:'שליחת ההזמנה בוואטסאפ',exact:true}).click();await p.waitForFunction(()=>window.previewOrders.length===1);const summary=await p.evaluate(()=>window.previewOrders[0]);for(const id of manifest.pizzas)assert(summary.includes(data.products.find(x=>x.id===id).name_he));assert.equal((summary.match(/תירס/g)||[]).length,3);assert.match(summary,/107/);assert.doesNotMatch(summary,/פרטי הבחירה לא נבחרו/);await p.screenshot({path:__dirname+'/screenshots/content-checkout-'+width+'.png'});
  await p.goto(A+'/login');await p.getByRole('button',{name:'התחברות',exact:true}).click();await p.getByRole('heading',{name:'דשבורד',exact:true}).waitFor();await p.goto(A+'/products');await p.getByRole('heading',{name:'מה זמין היום?',exact:true}).waitFor();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);for(const id of [...manifest.descriptionIds,...manifest.pizzas]){const product=data.products.find(x=>x.id===id);const row=p.locator(width<1000?'.product-card':'.product-row').filter({has:p.getByText(product.name_he,{exact:true})});assert.equal(await row.count(),1);assert.match(await row.locator('.product-price').innerText(),new RegExp(String(product.price_agorot/100)));}
  for(const id of ['drinks-02','cakes-01']){const r=await p.request.get(A+'/product-images/'+id+'.jpg');assert.equal(r.status(),200);assert.match(r.headers()['content-type'],/image\/jpeg/);}
  await p.screenshot({path:__dirname+'/screenshots/content-admin-'+width+'.png'});assert.equal(errors.length,0);results.push({width,status:'PASS',descriptions:28,images:2,pizzaGroups:3,singleRequiredFreeChoice:true,refresh:true,checkoutSummary:summary,adminPrices:true,adminMediaFiles:true,errors});await c.close();
 }
 for(const width of [390,1440]){const p=await b.newPage({viewport:{width,height:width===390?844:1000}});for(const id of ['drinks-02','cakes-01','bourekas-01']){await p.goto('http://127.0.0.1:4200/shop');const item=card(p,data.products.find(x=>x.id===id).name_he);await item.getByRole('button',{name:'הוספה',exact:true}).waitFor();await item.scrollIntoViewIfNeeded();await p.waitForTimeout(500);await item.screenshot({path:__dirname+'/screenshots/before-'+id+'-'+width+'.png'});await p.goto(U+'/shop');const after=card(p,data.products.find(x=>x.id===id).name_he);await after.scrollIntoViewIfNeeded();await p.waitForTimeout(300);await after.screenshot({path:__dirname+'/screenshots/after-'+id+'-'+width+'.png'});}await p.close();}
 await b.close();await fs.writeFile(__dirname+'/content-qa.json',JSON.stringify({status:'PASS',priceAndUnitMetadataUnchanged:78,results,adminLimitation:'Existing admin does not render descriptions, product photos or option editing; verified API content, asset routes and existing name/price/unit UI. No admin redesign.'},null,2));console.log('CONTENT RECOVERY QA PASS');
})().catch(e=>{console.error(e);process.exit(1)});
