import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, '..', '..');
const catalogPath = resolve(repositoryRoot, 'product-catalog-yachad.json');
const seedPath = resolve(scriptDirectory, '..', 'seed.sql');

const categoryIds = new Map([
  ['בורקסים', 'bourekas'],
  ['פיצות וסמבוסק', 'pizza-sambusak'],
  ['סלטים', 'salads'],
  ['כריכים וטוסטים', 'sandwiches-toasts'],
  ['מתוקים', 'sweets'],
  ['לחמי מחמצת', 'sourdough-breads'],
  ['עוגות', 'cakes'],
  ['עוגיות', 'cookies'],
  ['לחמניות ובייגלים', 'rolls-bagels'],
  ['שתייה', 'drinks'],
]);

function sqlText(value) {
  return `'${String(value ?? '').replaceAll("'", "''")}'`;
}

function sqlBoolean(value) {
  return value ? 'true' : 'false';
}

function sqlJson(value) {
  return `${sqlText(JSON.stringify(value))}::jsonb`;
}

const catalogSource = await readFile(catalogPath, 'utf8');
const catalog = JSON.parse(catalogSource);
const catalogHash = createHash('sha256').update(catalogSource).digest('hex');
const products = catalog.products ?? [];
const categoryNames = [...new Set(products.map((product) => product.category))];

if (products.length !== 78) throw new Error(`Expected 78 products, found ${products.length}.`);
if (categoryNames.length !== 10) throw new Error(`Expected 10 categories, found ${categoryNames.length}.`);

for (const categoryName of categoryNames) {
  if (!categoryIds.has(categoryName)) throw new Error(`Missing stable category id for: ${categoryName}`);
}

const categoryRows = categoryNames.map((name, index) =>
  `  (${sqlText(categoryIds.get(name))}, ${sqlText(name)}, ${index + 1}, true)`,
);

const productRows = products.map((product) =>
  `  (${[
    sqlText(product.id),
    sqlText(categoryIds.get(product.category)),
    sqlText(product.product_name),
    sqlText(product.description),
    Math.round(Number(product.price_ils) * 100),
    sqlText(product.image_url),
    sqlText(product.image_filename),
    sqlBoolean(product.active),
    true,
    sqlBoolean(product.available_for_delivery),
    sqlBoolean(product.available_for_pickup),
    Number(product.sort_order),
    sqlBoolean(product.has_options),
    sqlText(product.options_summary),
    sqlBoolean(product.owner_needs_to_confirm),
  ].join(', ')})`,
);

const metadataRows = products.map((product) =>
  `  (${sqlText(product.id)}, ${sqlText(catalogHash)}, ${sqlJson(product)})`,
);

const seed = `-- Generated by supabase/scripts/generate-seed.mjs. Do not edit by hand.
-- Source: product-catalog-yachad.json
-- SHA-256: ${catalogHash}
-- Products: ${products.length}; categories: ${categoryNames.length}

begin;

insert into public.categories (id, name_he, sort_order, active)
values
${categoryRows.join(',\n')}
on conflict (id) do update set
  name_he = excluded.name_he,
  sort_order = excluded.sort_order,
  active = excluded.active;

insert into public.products (
  id,
  category_id,
  name_he,
  description_he,
  price_agorot,
  image_url,
  image_filename,
  active,
  available_today,
  available_for_delivery,
  available_for_pickup,
  sort_order,
  has_options,
  options_summary,
  owner_needs_to_confirm
)
values
${productRows.join(',\n')}
on conflict (id) do update set
  category_id = excluded.category_id,
  name_he = excluded.name_he,
  description_he = excluded.description_he,
  price_agorot = excluded.price_agorot,
  image_url = excluded.image_url,
  image_filename = excluded.image_filename,
  active = excluded.active,
  available_today = excluded.available_today,
  available_for_delivery = excluded.available_for_delivery,
  available_for_pickup = excluded.available_for_pickup,
  sort_order = excluded.sort_order,
  has_options = excluded.has_options,
  options_summary = excluded.options_summary,
  owner_needs_to_confirm = excluded.owner_needs_to_confirm;

insert into public.product_source_metadata (product_id, catalog_sha256, source_payload)
values
${metadataRows.join(',\n')}
on conflict (product_id) do update set
  catalog_sha256 = excluded.catalog_sha256,
  source_payload = excluded.source_payload,
  imported_at = now();

insert into public.store_settings (
  id,
  ordering_enabled,
  delivery_enabled,
  pickup_enabled,
  customer_notice_active,
  customer_notice_type,
  customer_notice_text,
  customer_notice_start_at,
  customer_notice_end_at,
  delivery_fee_agorot,
  minimum_delivery_subtotal_agorot,
  pickup_fee_agorot
)
values (
  'default',
  true,
  true,
  true,
  false,
  'info',
  '',
  null,
  null,
  1500,
  7000,
  0
)
on conflict (id) do update set
  ordering_enabled = excluded.ordering_enabled,
  delivery_enabled = excluded.delivery_enabled,
  pickup_enabled = excluded.pickup_enabled,
  customer_notice_active = excluded.customer_notice_active,
  customer_notice_type = excluded.customer_notice_type,
  customer_notice_text = excluded.customer_notice_text,
  customer_notice_start_at = excluded.customer_notice_start_at,
  customer_notice_end_at = excluded.customer_notice_end_at,
  delivery_fee_agorot = excluded.delivery_fee_agorot,
  minimum_delivery_subtotal_agorot = excluded.minimum_delivery_subtotal_agorot,
  pickup_fee_agorot = excluded.pickup_fee_agorot;

do $$
begin
  if (select count(*) from public.categories) <> 10 then
    raise exception 'Bakery seed expected 10 categories';
  end if;

  if (select count(*) from public.products) <> 78 then
    raise exception 'Bakery seed expected 78 products';
  end if;

  if (select count(*) from public.product_source_metadata) <> 78 then
    raise exception 'Bakery seed expected 78 source metadata records';
  end if;
end;
$$;

commit;
`;

if (process.argv.includes('--check')) {
  const currentSeed = await readFile(seedPath, 'utf8');
  if (currentSeed !== seed) {
    throw new Error('supabase/seed.sql is stale. Run: node supabase/scripts/generate-seed.mjs');
  }
  console.log(`Seed is current: ${products.length} products, ${categoryNames.length} categories, ${catalogHash}`);
} else {
  await writeFile(seedPath, seed, 'utf8');
  console.log(`Wrote ${seedPath}: ${products.length} products, ${categoryNames.length} categories, ${catalogHash}`);
}
